import { Document, Page, Text, View, Image, StyleSheet } from '@react-pdf/renderer'
import { getNarrativeText } from './CertificateTemplates'

const styles = StyleSheet.create({
  page: {
    padding: 0,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  borderPage: {
    margin: '12mm',
    border: '2px solid #F97316',
    padding: '15mm',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
  },
  cornerContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  logo: {
    width: '70px',
    height: '70px',
    marginHorizontal: 'auto',
    marginTop: '5mm',
    marginBottom: '8mm',
  },
  header: {
    textAlign: 'center',
    marginBottom: '15mm',
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: '4px',
    color: '#111827',
  },
  headerText: {
    fontSize: 10,
    color: '#111827',
    marginBottom: '1px',
    lineHeight: 1.4,
  },
  headerContact: {
    fontSize: 9,
    color: '#6B7280',
    marginTop: '3px',
  },
  certTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F97316',
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: '15mm',
    marginTop: '5mm',
  },
  body: {
    fontSize: 11,
    lineHeight: 1.8,
    color: '#111827',
    textAlign: 'justify',
    marginBottom: '20mm',
  },
  signatureSection: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '8mm',
    marginTop: 'auto',
    paddingHorizontal: '10mm',
  },
  signatureBlock: {
    width: '40%',
    textAlign: 'center',
  },
  signatureLine: {
    borderTopWidth: 1,
    borderTopColor: '#111827',
    paddingTop: '3px',
    marginTop: '12mm',
    fontSize: 10,
    fontWeight: 'bold',
    color: '#111827',
  },
  footer: {
    textAlign: 'center',
    fontSize: 8,
    color: '#6B7280',
    marginBottom: '5mm',
    lineHeight: 1.5,
  },
})

interface CertificateData {
  certificate_no: string
  certificate_type: { name: string }
  patient: { full_name: string; patient_id: string }
  issue_date: string
  issued_by: string
  valid_from?: string
  valid_to?: string
  purpose?: string
  diagnosis?: string
  treatment_details?: string
  recommendations?: string
  restrictions?: string
  additional_notes?: string
}

export const CertificatePDF = ({
  certificate,
  logoUrl,
}: {
  certificate: CertificateData
  logoUrl: string
}) => {
  console.log('[PDF]', certificate.certificate_no, certificate.certificate_type?.name)
  const narrative = getNarrativeText(certificate.certificate_type.name, certificate as any)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.borderPage}>
          {/* Logo */}
          <Image style={styles.logo} src={logoUrl} />

          {/* Header */}
          <View style={styles.header}>
            <Text style={styles.headerTitle}>AYURSHALA PANCHAKARMA CENTER</Text>
            <Text style={styles.headerText}>SP-28, Wajidpur,</Text>
            <Text style={styles.headerText}>Sector-130, Noida – 201301</Text>
            <Text style={styles.headerContact}>+91-9821224767</Text>
            <Text style={styles.headerContact}>ayurshalapanchkarma@gmail.com</Text>
          </View>

          {/* Certificate Title */}
          <Text style={styles.certTitle}>{certificate.certificate_type.name}</Text>

          {/* Certificate Body */}
          <Text style={styles.body}>{narrative}</Text>

          {/* Signature Section */}
          <View style={styles.signatureSection}>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine}>
                <Text>Patient Signature</Text>
              </View>
            </View>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine}>
                <Text>{`Dr. ${certificate.issued_by}`}</Text>
                <Text style={{ fontSize: 9, marginTop: '2px' }}>
                  Ayurshala Panchakarma Center
                </Text>
              </View>
            </View>
          </View>

          {/* Footer */}
          <View style={styles.footer}>
            <Text>
              This certificate has been electronically generated by Ayurshala Panchakarma Center.
            </Text>
            <Text>No physical signature is required.</Text>
          </View>
        </View>
      </Page>
    </Document>
  )
}
